ens_job_index:
    path:     /
    defaults: { _controller: "EnsLionelBundle:Job:index" }
    methods:  GET

ens_job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsLionelBundle:Job:show" }
    methods:  GET
    requirements:
            id:  \d+

ens_job_new:
    path:     /new
    defaults: { _controller: "EnsLionelBundle:Job:new" }
    methods:  [GET, POST]

ens_job_create:
    path:     /create
    defaults: { _controller: "EnsLionelBundle:Job:create" }
    methods:  [GET, POST]

ens_job_edit:
    path:     /{id}/edit
    defaults: { _controller: "EnsLionelBundle:Job:edit" }
    methods:  [POST]

ens_job_update:
    path:     /{id}/update
    defaults: { _controller: "EnsLionelBundle:Job:update" }
    methods:  [POST]

ens_job_delete:
    path:     /{id}/delete
    defaults: { _controller: "EnsLionelBundle:Job:delete" }
    methods:  DELETE
