ens_lionel_ens_job:
    resource: "@EnsLionelBundle/Resources/config/routing/job.yml"
    prefix:   /ens_job

ens_lionel_homepage:
    path:     /
    defaults: { _controller: EnsLionelBundle:Default:index }
