ens_lionel_ens_job:
    resource: "@EnsLionelBundle/Resources/config/routing/job.yml"
    prefix:   /job

ens_lionel_homepage:
    path:     /hello/{name}
    defaults: { _controller: EnsLionelBundle:Default:index }

EnsLionelBundle_homepage:
    path:  /
    defaults: { _controller: EnsLionelBundle:Job:index }

EnsLionelBundle_category:
    path:  /category/{slug}/{page}
    defaults: { _controller: EnsLionelBundle:Category:show, page: 1 }