ens_lionel_ens_job:
    resource: "@EnsLionelBundle/Resources/config/routing/job.yml"
    prefix:   /job

ens_lionel_homepage:
    path:     /hello/{name}
    defaults: { _controller: EnsLionelBundle:Default:index }
